In [2]:
# import opencv
# 참조 1 : https://076923.github.io/posts/Python-opencv-1/
#참조 2 : https://stackoverflow.com/questions/1035340/reading-binary-file-and-looping-over-each-byte
# 강좌가 있는지는 확인이 필요함.
import cv2
import numpy as np
import sys

import io
from PIL import Image

In [2]:

i = 0
with open("./data/tube-sample.png", "rb") as f:
    byte = f.read(4)
    print(type(byte))

    # Do stuff with byte.
    byte = f.read(4096)
    decoded = np.fromstring(byte, dtype=np.uint8)
    print(decoded)
    cv2.namedWindow('image', cv2.WINDOW_NORMAL) # AUTOSIZE랑 다르게 창을 조절할 수 있다.
    cv2.imshow('image', decoded)
    cv2.waitKey()
    cv2.destroyAllWindows()


<class 'bytes'>
[ 13  10  26 ... 186 174 123]


C:\Users\sangt\AppData\Local\Temp/ipykernel_16720/1080573687.py:8: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  decoded = np.fromstring(byte, dtype=np.uint8)


In [3]:
# 파일 저장하기

slice = 0
with open("./data/tube-sample.png", "rb") as f:
    byte = f.read(16)
    while byte != b"":
        # Do stuff with byte.
        byte = f.read(4096)
        if (len(byte) == 0):
            break
        decoded = np.fromstring(byte, dtype=np.uint8)
        print(decoded)
        cv2.imwrite('./data/tube-sample_{}.png'.format(i), decoded)
        slice+=1
    print(slice)

[  0   0   9 ... 238  21   6]
[ 0  0  0 ... 22  0  0]
[0 0 0 ... 0 0 0]
[  0 128 109 ... 111  32 189]
[ 56 201 196 ... 237 149 179]
[217 236 112 ... 231 118  73]
[115 232 222 ... 195 122  41]
[229  92 243 ...  73 254 198]
[ 94  38 245 ...  14  74 106]
[188 239  53 ... 236 102 146]
[ 26 239 226 ...  36  69 222]
[105  73 146 ... 228 121 254]
[148  16 194 ... 135  75  73]
[146  84 235 ...  60 239 159]
[236 223  36 ...  47 202 174]
[ 51  72 127 ... 221 149 157]
[141 253 252 ... 101 199  27]
[242   0 128 ...  35  76  50]
[234 203  66 ... 187 151 121]
[144   1 128 ... 180  70  81]
[174 181 151 ...  16 187 181]
[121 158 239 ...   6 196 110]
[201 200 200 ... 244 248 142]
[145 148 114 ... 247 162  93]
[189   3  37 ...  25  35 201]
[242  21   0 ...  91  64  75]
[146 180 162 ...  66  96 130]
27


C:\Users\sangt\AppData\Local\Temp/ipykernel_16720/1591681318.py:11: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  decoded = np.fromstring(byte, dtype=np.uint8)


In [13]:
# 파일 저장하기2 : file read stream
# reshape 필요
# # 바이트로 슬라이스한 것을 보여주기

_IMAGE_SIZE = 100
#num_images = 1
_NUM_CHANNELS = 3
sliceSize = _IMAGE_SIZE * _IMAGE_SIZE * _NUM_CHANNELS
slice = 0

with open("./data/tube-sample.png", "rb") as bytestream:
    buf = bytestream.read(16)
    while buf != b"":
        buf = bytestream.read(sliceSize)
        if len(buf) < sliceSize:
            break
        data = np.frombuffer(buf, dtype=np.uint8)
        data = data.reshape(_IMAGE_SIZE, _IMAGE_SIZE, _NUM_CHANNELS)
        print(data)
        cv2.imwrite('./data/tube-sample_{}.png'.format(slice), data)
        slice+=1
    print(slice)

[[[  0   0   9]
  [ 96   0   0]
  [  8 207   8]
  ...
  [119 187 181]
  [220  90  21]
  [137  54  32]]

 [[104 213  34]
  [160  14  58]
  [165  74   8]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0 192 150]
  ...
  [  0   0   0]
  [128 227 146]
  [228 210 170]]

 ...

 [[ 92 204 102]
  [179 163 146]
  [188 201 146]
  ...
  [188 208 178]
  [ 70  82 231]
  [189 100  52]]

 [[ 26 237  48]
  [242   1 128]
  [ 57 218  89]
  ...
  [ 60  30 223]
  [210 196   7]
  [  0 230 169]]

 [[148 242  99]
  [206 102  11]
  [219 191  38]
  ...
  [  0 152  39]
  [159  58 220]
  [ 69 151 151]]]
[[[ 82  30 228]
  [209  12  75]
  [191  75  59]
  ...
  [250 237 146]
  [124 200 194]
  [ 71  82 207]]

 [[ 95   7  83]
  [ 74  57 205]
  [196   7   0]
  ...
  [157  47  43]
  [165  60 171]
  [148 242 176]]

 [[201 100 114]
  [ 71  63  37]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0 219  64]
  [146 231  88]]

 ...

 [[ 31  23 176]
  [218 229 255]
  [120  86  84]
  ..

In [16]:
# 파일 저장하기3 : file read stream
# reshape 필요
# # 바이트로 슬라이스한 것을 보여주기

_IMAGE_SIZE = 100
width = 200
height = 100
#num_images = 1
colorChannels = 3
sliceSize = width * height * colorChannels
slice = 0

with open("./data/tube-sample.png", "rb") as bytestream:
    buf = bytestream.read(16)
    while buf != b"":
        buf = bytestream.read(sliceSize)
        if len(buf) < sliceSize:
            break
        data = np.frombuffer(buf, dtype=np.uint8)
        data = data.reshape(height, width, colorChannels)
        #print(data)
        cv2.imwrite('./data/tube-sample_{}.png'.format(slice), data)
        slice+=1
    print(slice)

1


In [3]:
# Third party modules
import numpy
from PIL import Image


def get_image(image_path):
    """Get a numpy array of an image so that one can access values[x][y]."""
    image = Image.open(image_path, "r")
    width, height = image.size
    print(width, height)
    pixel_values = list(image.getdata())
    if image.mode == "RGB":
        channels = 3
    elif image.mode == "L":
        channels = 1
    elif image.mode == 'RGBA':
        channels = 4
    else:
        print("Unknown mode: %s" % image.mode)
        return None
    pixel_values = numpy.array(pixel_values).reshape((height,width, channels))
    return pixel_values


image = get_image("./data/tube-sample.png")
print(image.shape)
cv2.imshow('img1', image)
cv2.waitKey()
cv2.destroyAllWindows()


2400 2255
(2255, 2400, 4)


error: OpenCV(4.5.5) D:/a/opencv-python/opencv-python/opencv/modules/highgui/src/precomp.hpp:155: error: (-215:Assertion failed) src_depth != CV_16F && src_depth != CV_32S in function 'convertToShow'
